In [2]:
import pandas as pd
import numpy as np

In [92]:
df = pd.read_csv('전처리 완료.csv', encoding='utf-8-sig')

In [93]:
df.head()

,Country_Region,1/22/2020,1/23/2020,1/24/2020,1/25/2020,1/26/2020,1/27/2020,1/28/2020,1/29/2020,1/30/2020,...,6/08/2020,6/09/2020,6/10/2020,6/11/2020,6/12/2020,6/13/2020,6/14/2020,6/15/2020,6/16/2020,6/17/2020
0,Afghanistan,0,0,0,0,0,0,0,0,0,...,369,384,405,426,446,451,471,478,491,504
1,Albania,0,0,0,0,0,0,0,0,0,...,34,34,34,35,36,36,36,36,37,38
2,Algeria,0,0,0,0,0,0,0,0,0,...,715,724,732,741,751,760,767,777,788,799
3,Andorra,0,0,0,0,0,0,0,0,0,...,51,51,51,51,51,51,51,51,52,52
4,Angola,0,0,0,0,0,0,0,0,0,...,4,4,4,5,5,6,6,6,6,7

In [94]:
df_iso = pd.read_csv('COVID-19-master/csse_covid_19_data/UID_ISO_FIPS_LookUp_Table.csv', encoding = 'utf-8-sig', keep_default_na=False, na_values='')
df_iso.head()

,Unnamed: 0,Unnamed: 0.1,UID,iso2,iso3,code3,FIPS,Admin2,Province_State,Country_Region,Lat,Long_,Combined_Key
0,0,0,NaN,BW,NaN,NaN,NaN,NaN,NaN,Botswana,NaN,NaN,Botswana
1,1,1,NaN,BI,NaN,NaN,NaN,NaN,NaN,Burundi,NaN,NaN,Burundi
2,2,2,NaN,SL,NaN,NaN,NaN,NaN,NaN,Sierra Leone,NaN,NaN,Sierra Leone
3,3,3,4.0,AF,AFG,4.0,NaN,NaN,NaN,Afghanistan,33.93911,67.709953,Afghanistan
4,4,4,8.0,AL,ALB,8.0,NaN,NaN,NaN,Albania,41.15330,20.168300,Albania

In [95]:
df_iso = df_iso[['iso2', 'Country_Region']]

In [96]:
df_iso = df_iso.drop_duplicates(subset = 'Country_Region', keep='last')

In [97]:
df_merge = pd.merge(df, df_iso, how = 'left', on = 'Country_Region')

In [98]:
df = df_merge.dropna(subset = ['iso2'])

In [99]:
def flag(row):
    flag_link = 'https://www.countryflags.io/' + row + '/flat/64.png'
    return flag_link

df['iso2'] = df['iso2'].apply(flag)

<ipython-input-99-b815ea101c9d>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['iso2'] = df['iso2'].apply(flag)

In [101]:
df

,Country_Region,1/22/2020,1/23/2020,1/24/2020,1/25/2020,1/26/2020,1/27/2020,1/28/2020,1/29/2020,1/30/2020,...,6/09/2020,6/10/2020,6/11/2020,6/12/2020,6/13/2020,6/14/2020,6/15/2020,6/16/2020,6/17/2020,iso2
0,Afghanistan,0,0,0,0,0,0,0,0,0,...,384,405,426,446,451,471,478,491,504,https://www.countryflags.io/AF/flat/64.png
1,Albania,0,0,0,0,0,0,0,0,0,...,34,34,35,36,36,36,36,37,38,https://www.countryflags.io/AL/flat/64.png
2,Algeria,0,0,0,0,0,0,0,0,0,...,724,732,741,751,760,767,777,788,799,https://www.countryflags.io/DZ/flat/64.png
3,Andorra,0,0,0,0,0,0,0,0,0,...,51,51,51,51,51,51,51,52,52,https://www.countryflags.io/AD/flat/64.png
4,Angola,0,0,0,0,0,0,0,0,0,...,4,4,5,5,6,6,6,6,7,https://www.countryflags.io/AO/flat/64.png
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181,Venezuela,0,0,0,0,0,0,0,0,0,...,23,23,23,23,24,25,26,27,28,https://www.countryflags.io/VE/flat/64.png
182,Vietnam,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,https://www.countryflags.io/VN/flat/64.png
183,West Bank and Gaza,0,0,0,0,0,0,0,0,0,...,3,3,3,3,3,3,3,3,3,https://www.countryflags.io/PS/flat/64.png
185,Zambia,0,0,0,0,0,0,0,0,0,...,10,10,10,10,10,11,11,11,11,https://www.countryflags.io/ZM/flat/64.png
186,Zimbabwe,0,0,0,0,0,0,0,0,0,...,4,4,4,4,4,4,4,4,4,https://www.countryflags.io/ZW/flat/64.png

In [102]:
cols = df.columns.tolist()
cols.remove('iso2')
cols.insert(1,'iso2')
df = df[cols]

In [103]:
df

,Country_Region,iso2,1/22/2020,1/23/2020,1/24/2020,1/25/2020,1/26/2020,1/27/2020,1/28/2020,1/29/2020,...,6/08/2020,6/09/2020,6/10/2020,6/11/2020,6/12/2020,6/13/2020,6/14/2020,6/15/2020,6/16/2020,6/17/2020
0,Afghanistan,https://www.countryflags.io/AF/flat/64.png,0,0,0,0,0,0,0,0,...,369,384,405,426,446,451,471,478,491,504
1,Albania,https://www.countryflags.io/AL/flat/64.png,0,0,0,0,0,0,0,0,...,34,34,34,35,36,36,36,36,37,38
2,Algeria,https://www.countryflags.io/DZ/flat/64.png,0,0,0,0,0,0,0,0,...,715,724,732,741,751,760,767,777,788,799
3,Andorra,https://www.countryflags.io/AD/flat/64.png,0,0,0,0,0,0,0,0,...,51,51,51,51,51,51,51,51,52,52
4,Angola,https://www.countryflags.io/AO/flat/64.png,0,0,0,0,0,0,0,0,...,4,4,4,5,5,6,6,6,6,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181,Venezuela,https://www.countryflags.io/VE/flat/64.png,0,0,0,0,0,0,0,0,...,22,23,23,23,23,24,25,26,27,28
182,Vietnam,https://www.countryflags.io/VN/flat/64.png,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
183,West Bank and Gaza,https://www.countryflags.io/PS/flat/64.png,0,0,0,0,0,0,0,0,...,3,3,3,3,3,3,3,3,3,3
185,Zambia,https://www.countryflags.io/ZM/flat/64.png,0,0,0,0,0,0,0,0,...,10,10,10,10,10,10,11,11,11,11
186,Zimbabwe,https://www.countryflags.io/ZW/flat/64.png,0,0,0,0,0,0,0,0,...,4,4,4,4,4,4,4,4,4,4

In [104]:
cols[1] = 'country_flag'

In [105]:
df.columns = cols

In [106]:
df

,Country_Region,country_flag,1/22/2020,1/23/2020,1/24/2020,1/25/2020,1/26/2020,1/27/2020,1/28/2020,1/29/2020,...,6/08/2020,6/09/2020,6/10/2020,6/11/2020,6/12/2020,6/13/2020,6/14/2020,6/15/2020,6/16/2020,6/17/2020
0,Afghanistan,https://www.countryflags.io/AF/flat/64.png,0,0,0,0,0,0,0,0,...,369,384,405,426,446,451,471,478,491,504
1,Albania,https://www.countryflags.io/AL/flat/64.png,0,0,0,0,0,0,0,0,...,34,34,34,35,36,36,36,36,37,38
2,Algeria,https://www.countryflags.io/DZ/flat/64.png,0,0,0,0,0,0,0,0,...,715,724,732,741,751,760,767,777,788,799
3,Andorra,https://www.countryflags.io/AD/flat/64.png,0,0,0,0,0,0,0,0,...,51,51,51,51,51,51,51,51,52,52
4,Angola,https://www.countryflags.io/AO/flat/64.png,0,0,0,0,0,0,0,0,...,4,4,4,5,5,6,6,6,6,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181,Venezuela,https://www.countryflags.io/VE/flat/64.png,0,0,0,0,0,0,0,0,...,22,23,23,23,23,24,25,26,27,28
182,Vietnam,https://www.countryflags.io/VN/flat/64.png,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
183,West Bank and Gaza,https://www.countryflags.io/PS/flat/64.png,0,0,0,0,0,0,0,0,...,3,3,3,3,3,3,3,3,3,3
185,Zambia,https://www.countryflags.io/ZM/flat/64.png,0,0,0,0,0,0,0,0,...,10,10,10,10,10,10,11,11,11,11
186,Zimbabwe,https://www.countryflags.io/ZW/flat/64.png,0,0,0,0,0,0,0,0,...,4,4,4,4,4,4,4,4,4,4

In [107]:
df.to_csv('최종 시각화용 파일.csv')