In [66]:
import pandas as pd
import numpy as np
import json
import os

In [47]:
path = 'COVID-19-master/csse_covid_19_data/csse_covid_19_daily_reports/'
data = '01-22-2020.csv'
df = pd.read_csv(path + data, encoding = 'utf-8-sig')
df

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,Anhui,Mainland China,1/22/2020 17:00,1.0,NaN,NaN
1,Beijing,Mainland China,1/22/2020 17:00,14.0,NaN,NaN
2,Chongqing,Mainland China,1/22/2020 17:00,6.0,NaN,NaN
3,Fujian,Mainland China,1/22/2020 17:00,1.0,NaN,NaN
4,Gansu,Mainland China,1/22/2020 17:00,NaN,NaN,NaN
5,Guangdong,Mainland China,1/22/2020 17:00,26.0,NaN,NaN
6,Guangxi,Mainland China,1/22/2020 17:00,2.0,NaN,NaN
7,Guizhou,Mainland China,1/22/2020 17:00,1.0,NaN,NaN
8,Hainan,Mainland China,1/22/2020 17:00,4.0,NaN,NaN
9,Hebei,Mainland China,1/22/2020 17:00,1.0,NaN,NaN
10,Heilongjiang,Mainland China,1/22/2020 17:00,NaN,NaN,NaN
11,Henan,Mainland China,1/22/2020 17:00,5.0,NaN,NaN
12,Hong Kong,Hong Kong,1/22/2020 17:00,NaN,NaN,NaN
13,Hubei,Mainland China,1/22/2020 17:00,444.0,17.0,28.0
14,Hunan,Mainland China,1/22/2020 17:00,4.0,NaN,NaN
15,Inner Mongolia,Mainland China,1/22/2020 17:00,NaN,NaN,NaN
16,Jiangsu,Mainland China,1/22/2020 17:00,1.0,NaN,NaN
17,Jiangxi,Mainland China,1/22/2020 17:00,2.0,NaN,NaN
18,Jilin,Mainland China,1/22/2020 17:00,NaN,NaN,NaN
19,Liaoning,Mainland China,1/22/2020 17:00,2.0,NaN,NaN
20,Macau,Macau,1/22/2020 17:00,1.0,NaN,NaN
21,Ningxia,Mainland China,1/22/2020 17:00,1.0,NaN,NaN
22,Qinghai,Mainland China,1/22/2020 17:00,NaN,NaN,NaN
23,Shaanxi,Mainland China,1/22/2020 17:00,NaN,NaN,NaN
24,Shandong,Mainland China,1/22/2020 17:00,2.0,NaN,NaN
25,Shanghai,Mainland China,1/22/2020 17:00,9.0,NaN,NaN
26,Shanxi,Mainland China,1/22/2020 17:00,1.0,NaN,NaN
27,Sichuan,Mainland China,1/22/2020 17:00,5.0,NaN,NaN
28,Taiwan,Taiwan,1/22/2020 17:00,1.0,NaN,NaN
29,Tianjin,Mainland China,1/22/2020 17:00,4.0,NaN,NaN
30,Tibet,Mainland China,1/22/2020 17:00,NaN,NaN,NaN
31,Washington,US,1/22/2020 17:00,1.0,NaN,NaN
32,Xinjiang,Mainland China,1/22/2020 17:00,NaN,NaN,NaN
33,Yunnan,Mainland China,1/22/2020 17:00,1.0,NaN,NaN
34,Zhejiang,Mainland China,1/22/2020 17:00,10.0,NaN,NaN
35,NaN,Japan,1/22/2020 17:00,2.0,NaN,NaN
36,NaN,Thailand,1/22/2020 17:00,2.0,NaN,NaN
37,NaN,South Korea,1/22/2020 17:00,1.0,NaN,NaN

In [48]:
df = df[['Province/State','Country/Region','Deaths']]
df.columns = df.columns.str.replace('/','_')

In [49]:
with open('COVID-19-master/csse_covid_19_data/country_convert.json', 'r', encoding = 'utf-8-sig') as json_file:
    json_data = json.load(json_file)
json_data

{'Mainland China': 'China',
 'Macau': 'China',
 'South Korea': 'Korea, South',
 'Aruba': 'Netherlands',
 ' Azerbaijan': 'Azerbaijan',
 'Bahamas, The': 'Bahamas',
 'Cape Verde': 'Cabo Verde',
 'Cayman Islands': 'United Kingdom',
 'Channel Islands': 'United Kingdom',
 'Curacao': 'Netherlands',
 'Czech Republic': 'Czechia',
 'East Timor': 'Timor-Leste',
 'Faroe Islands': 'Denmark',
 'French Guiana': 'France',
 'Gambia, The': 'Gambia',
 'Gibraltar': 'United Kingdom',
 'Greenland': 'Denmark',
 'Guadeloupe': 'France',
 'Guam': 'US',
 'Guernsey': 'US',
 'Hong Kong': 'China',
 'Hong Kong SAR': 'China',
 'Iran (Islamic Republic of)': 'Iran',
 'Ivory Coast': "Cote d'Ivoire",
 'Jersey': 'US',
 'Macao SAR': 'China',
 'Martinique': 'France',
 'Mayotte': 'France',
 'North Ireland': 'United Kingdom',
 'Palestine': 'West Bank and Gaza',
 'Puerto Rico': 'US',
 'Republic of Ireland': 'Ireland',
 'Republic of Korea': 'Korea, South',
 'Republic of Moldova': 'Moldova',
 'Republic of the Congo': 'Congo (Brazzaville)',
 'Reunion': 'France',
 'Russian Federation': 'Russia',
 'Saint Barthelemy': 'France',
 'Saint Martin': 'France',
 'St. Martin': 'US',
 'Taipei and environs': 'Taiwan',
 'The Bahamas': 'Bahamas',
 'The Gambia': 'Gambia',
 'UK': 'United Kingdom',
 'Vatican City': 'Holy See',
 'Viet Nam': 'Vietnam',
 'occupied Palestinian territory': 'West Bank and Gaza',
 'Taiwan*': 'Taiwan',
 'Malawi': 'France',
 'South Sudan': 'Sudan',
 'Western Sahara': 'Morocco',
 'Namibia': 'Namibia'}

In [50]:
def country_name_change(df):
    if df['Country_Region'] in json_data:
        df['Country_Region'] = json_data[df['Country_Region']]
    return df

In [51]:
df = df.apply(country_name_change, axis = 1)

In [52]:
dates = data.split('.')[0].lstrip('0').replace('-','/')

In [53]:
df.columns = ['Province_State','Country_Region', dates]

In [55]:
df.head()

  Province_State Country_Region  1/22/2020
0          Anhui          China        NaN
1        Beijing          China        NaN
2      Chongqing          China        NaN
3         Fujian          China        NaN
4          Gansu          China        NaN

In [64]:
df = df.dropna(subset=['1/22/2020'])

In [65]:
df.astype({'1/22/2020':'int64'})

   Province_State Country_Region  1/22/2020
13          Hubei          China         17

In [110]:
path = 'COVID-19-master/csse_covid_19_data/csse_covid_19_daily_reports/'

with open('COVID-19-master/csse_covid_19_data/country_convert.json', 'r', encoding = 'utf-8-sig') as json_file:
    json_data = json.load(json_file)

def country_name_change(df):
    if df['Country_Region'] in json_data:
        df['Country_Region'] = json_data[df['Country_Region']]
    return df['Country_Region']

def create_df(data):
    df = pd.read_csv(path + data, encoding = 'utf-8-sig')
    try:
        df = df[['Country_Region','Deaths']]
    except:
        df = df[['Country/Region','Deaths']]
        df.columns = df.columns.str.replace('/','_')

    df = df.dropna(subset=['Deaths'])
    df['Country_Region'] = df.apply(country_name_change, axis = 1)
    df.astype({'Deaths':'int64'})
    df = df.groupby('Country_Region').sum()

    dates = data.split('.')[0].lstrip('0').replace('-','/')
    df.columns = [dates]

    return df

In [113]:
def merge_df(path):
    
    file_list, csv_list = os.listdir(path), list()
    df_first = True
    

    for file in file_list:
        if file.split('.')[-1] == 'csv':
            csv_list.append(file)
    csv_list.sort()
    
    for file in csv_list:
        df = create_df(file)
        if df_first:
            df_final, df_first = df, False
        else:
            df_final = pd.merge(df_final, df, how = 'outer', left_index = True, right_index  =True)

    df_final = df_final.fillna(0)
    return df_final

In [114]:
path = 'COVID-19-master/csse_covid_19_data/csse_covid_19_daily_reports/'
df = merge_df(path)
df

,1/22/2020,1/23/2020,1/24/2020,1/25/2020,1/26/2020,1/27/2020,1/28/2020,1/29/2020,1/30/2020,1/31/2020,...,6/08/2020,6/09/2020,6/10/2020,6/11/2020,6/12/2020,6/13/2020,6/14/2020,6/15/2020,6/16/2020,6/17/2020
Country_Region,,,,,,,,,,,,,,,,,,,,,
Afghanistan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,369.0,384.0,405.0,426.0,446.0,451.0,471.0,478.0,491.0,504.0
Albania,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,34.0,34.0,34.0,35.0,36.0,36.0,36.0,36.0,37.0,38.0
Algeria,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,715.0,724.0,732.0,741.0,751.0,760.0,767.0,777.0,788.0,799.0
Andorra,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,51.0,51.0,51.0,51.0,51.0,51.0,51.0,51.0,52.0,52.0
Angola,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,4.0,4.0,5.0,5.0,6.0,6.0,6.0,6.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Vietnam,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
West Bank and Gaza,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
Yemen,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,112.0,127.0,129.0,136.0,139.0,160.0,164.0,208.0,214.0,244.0
Zambia,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,10.0,10.0,10.0,10.0,10.0,11.0,11.0,11.0,11.0
Zimbabwe,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0

In [116]:
df = df.astype('int64')
df

,1/22/2020,1/23/2020,1/24/2020,1/25/2020,1/26/2020,1/27/2020,1/28/2020,1/29/2020,1/30/2020,1/31/2020,...,6/08/2020,6/09/2020,6/10/2020,6/11/2020,6/12/2020,6/13/2020,6/14/2020,6/15/2020,6/16/2020,6/17/2020
Country_Region,,,,,,,,,,,,,,,,,,,,,
Afghanistan,0,0,0,0,0,0,0,0,0,0,...,369,384,405,426,446,451,471,478,491,504
Albania,0,0,0,0,0,0,0,0,0,0,...,34,34,34,35,36,36,36,36,37,38
Algeria,0,0,0,0,0,0,0,0,0,0,...,715,724,732,741,751,760,767,777,788,799
Andorra,0,0,0,0,0,0,0,0,0,0,...,51,51,51,51,51,51,51,51,52,52
Angola,0,0,0,0,0,0,0,0,0,0,...,4,4,4,5,5,6,6,6,6,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Vietnam,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
West Bank and Gaza,0,0,0,0,0,0,0,0,0,0,...,3,3,3,3,3,3,3,3,3,3
Yemen,0,0,0,0,0,0,0,0,0,0,...,112,127,129,136,139,160,164,208,214,244
Zambia,0,0,0,0,0,0,0,0,0,0,...,10,10,10,10,10,10,11,11,11,11
Zimbabwe,0,0,0,0,0,0,0,0,0,0,...,4,4,4,4,4,4,4,4,4,4

In [118]:
df.to_csv('전처리 완료.csv')